<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEhjdkku\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEhjdkku/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEhjdkku.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEhjdkku\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEhjdkku\appProdProjectContainer(array(
    'container.build_hash' => 'Ehjdkku',
    'container.build_id' => 'adb14980',
    'container.build_time' => 1544121050,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEhjdkku');
